version: 0.0
    os: linux
    files:
      - source: /
        destination: /opt/laravel/
        overwrite: true
    file_exists_behavior: OVERWRITE
    BeforeInstall:
    - location: deploy/beforeinstall.sh
      timeout: 300
      runas: root
      AfterInstall:
    - location: deploy/afterinstall.sh
      timeout: 300
      runas: root
      

