version: 0.0
os: ubuntu
files:
  - source: s3://demo-code-deploy190723/code_file.zip
    destination: /opt/laravel/
hooks:
  BeforeInstall:
    - location: deploy/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/afterinstall.sh
      timeout: 300
      runas: root   
 


