name: Upload Staging Branch Code to S3

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  

      - name: Build .zip archive
        run: |
          zip -r code-file.zip .
          echo "Successfully created code-file.zip"

      - name: Upload .zip to S3
        run: |
          aws s3 cp code-file.zip s3://example2607/code-file.zip
          echo "Uploaded code-file.zip to S3 bucket"
          
          
      - name: Trigger the code-deploy service
        run: |
           aws deploy push --application-name Example --s3-location s3://example2607/code-file.zip --region ap-south-1
           aws deploy create-deployment --application-name Example --s3-location bucket=example2607,key=code-file.zip,bundleType=zip --deployment-group-name Example-group --deployment-config-name CodeDeployDefault.AllAtOnce
